volumes:
  zk1-data:
  zk1-logs:
  zk2-data:
  zk2-logs:
  zk3-data:
  zk3-logs:
  broker01-data:
  broker02-data:
  broker03-data:
services:
  zk1:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zk1
    container_name: zk1
    ports:
      - 42181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAX_CLIENT_CNXNS: 0
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - zk1-data:/var/lib/zookeeper/data
      - zk1-logs:/var/lib/zookeeper/log
  zk2:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zk2
    container_name: zk2
    ports:
      - 42182:2181
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAX_CLIENT_CNXNS: 0
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - zk2-data:/var/lib/zookeeper/data
      - zk2-logs:/var/lib/zookeeper/log
  zk3:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zk3
    container_name: zk3
    ports:
      - 42183:2181
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAX_CLIENT_CNXNS: 0
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - zk3-data:/var/lib/zookeeper/data
      - zk3-logs:/var/lib/zookeeper/log
  zoonavigator-api:
    image: elkozmon/zoonavigator-api:latest
    hostname: zoonavigator-api
    container_name: zoonavigator-api
    # ports:
    #   - 49001:9001
    environment:
      API_HTTP_PORT: 9001
    depends_on:
      - zk1
      - zk2
      - zk3
    restart: always
  zoonavigator-web:
    image: elkozmon/zoonavigator-web:latest
    hostname: zoonavigator-web
    container_name: zoonavigator-web
    ports:
      - 49002:8001 # connection string: "zk1:2181,zk2:2181,zk3:2181"
    environment:
      API_HOST: zoonavigator-api
      API_PORT: 9001
      WEB_HTTP_PORT: 8001
    depends_on:
      - zoonavigator_api
    restart: always
  broker01:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker01
    container_name: broker01
    ports:
      - 49092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: broker01
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker01:9092
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULTS_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168 # 1 week
      KAFKA_LOG_SEGMENT_BYTES: 1073741824 # 1GB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 # 5 min
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000 # 1 min
      KAFKA_SCHEMA_REGISTRY_URL: http://registry1:8081,http://registry2:8081
    volumes:
      - broker01-data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3
  broker02:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker02
    container_name: broker02
    ports:
      - 49093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: broker02
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker02:9092
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULTS_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168 # 1 week
      KAFKA_LOG_SEGMENT_BYTES: 1073741824 # 1GB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 # 5 min
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000 # 1 min
      KAFKA_SCHEMA_REGISTRY_URL: http://registry1:8081,http://registry2:8081
    volumes:
      - broker02-data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3
  broker03:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker03
    container_name: broker03
    ports:
      - 49094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: broker03
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker03:9092
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULTS_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168 # 1 week
      KAFKA_LOG_SEGMENT_BYTES: 1073741824 # 1GB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 # 5 min
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000 # 1 min
      KAFKA_SCHEMA_REGISTRY_URL: http://registry1:8081,http://registry2:8081
    volumes:
      - broker03-data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3
  cmak:
    container_name: cmak
    image: vimagick/cmak
    environment:
      ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
      KAFKA_MANAGER_AUTH_ENABLED: "false"
      # KAFKA_MANAGER_AUTH_ENABLED: true
      # KAFKA_MANAGER_USERNAME: admin
      # KAFKA_MANAGER_PASSWORD: admin
    ports:
      - 49000:9000
    depends_on:
      - broker01
      - broker02
      - broker03
    healthcheck:
      test: curl -f http://cmak:9000/api/health || exit 1
    restart: unless-stopped
  registry1:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: registry1
    container_name: registry1
    ports:
      - 48081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker01:9092,PLAINTEXT://broker02:9092,PLAINTEXT://broker03:9092
      SCHEMA_REGISTRY_HOST_NAME: registry1
      SCHEMA_REGISTRY_LISTENERS: http://registry1:8081
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
  registry2:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: registry2
    container_name: registry2
    ports:
      - 48181:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker01:9092,PLAINTEXT://broker02:9092,PLAINTEXT://broker03:9092
      SCHEMA_REGISTRY_HOST_NAME: registry2
      SCHEMA_REGISTRY_LISTENERS: http://registry2:8081
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
  registry-ui:
    image: landoop/schema-registry-ui:latest
    hostname: registry-ui
    container_name: registry-ui
    ports:
      - 48001:8000
    volumes:
      - ./registry-ui.env.js:/schema-registry-ui/env.js
    depends_on:
      - registry_1
      - registry_2
  restproxy1:
    image: confluentinc/cp-kafka-rest:6.2.0
    hostname: restproxy1
    container_name: restproxy1
    ports:
      - 48082:8082
    environment:
      KAFKA_REST_ID: 1
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://broker01:9092,PLAINTEXT://broker02:9092,PLAINTEXT://broker03:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_HOST_NAME: restproxy1
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://registry1:8081
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ACKS: all
    depends_on:
      - broker01
      - broker02
      - broker03
      - registry1
  restproxy2:
    image: confluentinc/cp-kafka-rest:6.2.0
    hostname: restproxy2
    container_name: restproxy2
    ports:
      - 48182:8082
    environment:
      KAFKA_REST_ID: 2
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://broker01:9092,PLAINTEXT://broker02:9092,PLAINTEXT://broker03:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_HOST_NAME: restproxy2
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://registry2:8081
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ACKS: all
    depends_on:
      - broker01
      - broker02
      - broker03
      - registry2
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:latest
    hostname: kafka-topics-ui
    container_name: kafka-topics-ui
    ports:
      - 48000:8000
    volumes:
      - ./kafka-topics-ui.env.js:/kafka-topics-ui/env.js
    depends_on:
      - broker01
      - broker02
      - broker03
      - restproxy1
      - restproxy2
