services:
  zookeeper_1:
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    environment:
      ZOO_MY_ID: 1
    ports:
      - 2181:2181 # ZooKeeper
      - 8011:80   # AdminServer http://localhost:8011/commands
    volumes:
      - data_zookeeper_1:/data/zookeeper
      - kafka_logs_1:/kafka/logs
  zookeeper_2:
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    environment:
      ZOO_MY_ID: 2
    ports:
      - 2182:2181 # ZooKeeper
      - 8012:80   # AdminServer http://localhost:8012/commands
    volumes:
      - data_zookeeper_2:/data/zookeeper
      - kafka_logs_2:/kafka/logs
  zookeeper_3:
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    environment:
      ZOO_MY_ID: 3
    ports:
      - 2183:2181 # ZooKeeper
      - 8013:80   # AdminServer http://localhost:8013/commands
    volumes:
      - data_zookeeper_3:/data/zookeeper
      - kafka_logs_3:/kafka/logs
volumes:
  data_zookeeper_1:
  data_zookeeper_2:
  data_zookeeper_3:
  kafka_logs_1:
  kafka_logs_2:
  kafka_logs_3:
